spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-old-field-amdswspz-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DLuIwi9ezrC8


google.client.id=TU_CLIENT_ID

jwt.secret=super_secret_key_123
jwt.expiration=86400000